# Generated by Django 4.1.5 on 2023-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            (
                                "Real Nigerian Instagram Follower",
                                "Real Nigerian Instagram Follower",
                            ),
                            (
                                "Instagram Reach + Impressions + Profile Visits [Post Link]",
                                "Instagram Reach + Impressions + Profile Visits [Post Link]",
                            ),
                            (
                                "Instagram Reach + Impressions [Post Link]",
                                "Instagram Reach + Impressions [Post Link]",
                            ),
                            ("Instagram Emoji Comments", "Instagram Emoji Comments"),
                            ("Instagram Random Comments", "Instagram Random Comments"),
                            (
                                "Instagram Likes [Post Link]",
                                "Instagram Likes [Post Link]",
                            ),
                            ("Instagram Followers", "Instagram Followers"),
                        ],
                        default=(
                            "Real Nigerian Instagram Follower",
                            "Real Nigerian Instagram Follower",
                        ),
                        max_length=200,
                    ),
                ),
                ("price", models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="depositlog",
            old_name="dateway",
            new_name="gateway",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
