# Generated by Django 4.1.5 on 2023-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_instagramservice_rename_dateway_depositlog_gateway_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Tiktok Like [Post Link]", "Tiktok Like [Post Link]"),
                            ("TikTok Followers", "TikTok Followers"),
                            (
                                "Cheapest TikTok Video Views [Post Link]",
                                "Cheapest TikTok Video Views [Post Link]s",
                            ),
                        ],
                        default=("Tiktok Like [Post Link]", "Tiktok Like [Post Link]"),
                        max_length=200,
                    ),
                ),
                ("price", models.FloatField(default=0)),
            ],
        ),
    ]
