# Generated by Django 4.1.5 on 2023-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tiktokservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            (
                                "Youtube Views [RECOMMENDED]",
                                "Youtube Views [RECOMMENDED]",
                            ),
                            ("Youtube Subscribers", "Youtube Subscribers"),
                            ("Youtube Likes", "Youtube Likes"),
                        ],
                        default=(
                            "Youtube Views [RECOMMENDED]",
                            "Youtube Views [RECOMMENDED]",
                        ),
                        max_length=200,
                    ),
                ),
                ("price", models.FloatField(default=0)),
            ],
        ),
    ]
