# Generated by Django 4.1.5 on 2023-01-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_depositpreview_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Real Nigerian Instagram Follower",
                                "Real Nigerian Instagram Follower",
                            ),
                            (
                                "Instagram Reach + Impressions + Profile Visits [Post Link]",
                                "Instagram Reach + Impressions + Profile Visits [Post Link]",
                            ),
                            (
                                "Instagram Reach + Impressions [Post Link]",
                                "Instagram Reach + Impressions [Post Link]",
                            ),
                            ("Instagram Emoji Comments", "Instagram Emoji Comments"),
                            ("Instagram Random Comments", "Instagram Random Comments"),
                            (
                                "Instagram Likes [Post Link]",
                                "Instagram Likes [Post Link]",
                            ),
                            ("Instagram Followers", "Instagram Followers"),
                            ("Tiktok Like [Post Link]", "Tiktok Like [Post Link]"),
                            ("TikTok Followers", "TikTok Followers"),
                            (
                                "Cheapest TikTok Video Views [Post Link]",
                                "Cheapest TikTok Video Views [Post Link]s",
                            ),
                            (
                                "Youtube Views [RECOMMENDED]",
                                "Youtube Views [RECOMMENDED]",
                            ),
                            ("Youtube Subscribers", "Youtube Subscribers"),
                            ("Youtube Likes", "Youtube Likes"),
                        ],
                        default="choose",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("mininum", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField()),
                ("price_per_k", models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="InstagramService",
        ),
        migrations.DeleteModel(
            name="TikTokService",
        ),
        migrations.DeleteModel(
            name="YoutubeService",
        ),
    ]
