# Generated by Django 4.1.5 on 2023-01-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_instagramservice_service_id_tiktokservice_service_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instagramservice",
            old_name="mininum",
            new_name="minimum",
        ),
        migrations.RenameField(
            model_name="tiktokservice",
            old_name="mininum",
            new_name="minimum",
        ),
        migrations.RenameField(
            model_name="youtubeservice",
            old_name="mininum",
            new_name="minimum",
        ),
    ]
