# Generated by Django 4.1.5 on 2023-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_orderhistory_options_depositlog_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositlog",
            name="gateway",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="depositlog",
            name="status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
