# Generated by Django 4.1.5 on 2023-01-21 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_depositlog_gateway_alter_depositlog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="charge",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="post_balance",
        ),
        migrations.AddField(
            model_name="transaction",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
