# Generated by Django 4.1.5 on 2023-01-25 01:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_courierservice_receiver_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courierservice",
            name="tracking_id",
            field=models.UUIDField(
                default=core.models.create_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
