# Generated by Django 4.1.5 on 2023-01-25 01:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_courierservice_tracking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courierservice",
            name="tracking_id",
            field=models.CharField(
                default=core.models.create_id,
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
