# Generated by Django 4.1.5 on 2023-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_contactsupport"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsupport",
            name="subject",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
