# Generated by Django 4.1.5 on 2023-01-26 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_contactsupport_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courierservice",
            old_name="receiver_company_name",
            new_name="receiver_shipping_fee",
        ),
        migrations.RemoveField(
            model_name="courierservice",
            name="sender_company_name",
        ),
        migrations.AddField(
            model_name="courierservice",
            name="sender_package",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
