# Generated by Django 4.1.5 on 2023-01-26 15:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0027_rename_receiver_company_name_courierservice_receiver_shipping_fee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="courierservice",
            name="tracking_id",
            field=models.CharField(
                default=core.models.create_id,
                editable=False,
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
